# Generated by Django 3.0.4 on 2020-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.CharField(default='visit', max_length=10),
        ),
    ]
