# Generated by Django 3.0.4 on 2020-06-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200605_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_long',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
