# Generated by Django 3.0.4 on 2020-06-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200605_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
