# Generated by Django 3.0.4 on 2020-06-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_textile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialLubricant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('description_long', models.TextField(max_length=600, null=True)),
                ('description_short', models.TextField(max_length=150, null=True)),
                ('category', models.CharField(choices=[('Metal Working Fluids', 'Metal Working Fluids'), ('Compressor Oil', 'Compressor Oil'), ('Rust Preventive Oil', 'Rust Preventive Oil'), ('Aluminium Wire Drawing Oil', 'Aluminium Wire Drawing Oil'), ('Hydraulic Oil', 'Hydraulic Oil')], max_length=200, null=True)),
                ('image_1', models.ImageField(blank=True, upload_to='product_image/')),
                ('image_2', models.ImageField(blank=True, upload_to='product_image/')),
                ('image_3', models.ImageField(blank=True, upload_to='product_image/')),
            ],
        ),
        migrations.RenameModel(
            old_name='AutomotiveLubricants',
            new_name='AutomotiveLubricant',
        ),
        migrations.RenameModel(
            old_name='Sulfonates',
            new_name='Sulfonate',
        ),
        migrations.DeleteModel(
            name='IndustrialLubricants',
        ),
    ]
